/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux ubuntu 4.15.0-50-generic x86_64"
#define LGL_COMPILED "Tue May 21 07:33:36 PDT 2019"
#define LGL_RELEASED "Don Mai 22 22:08:00 CEST 2014"
#define LGL_VERSION "azf"
#define LGL_ID "92032848c138b2f33629ad24394d60a3787a1046"
